# config
cover: /img/bg.jpg
logo: /img/logo.png
top_saying:
- title: Learning to <b>Live</b>. Learning to <b>Love</b>. Learning to <b>Code</b>. 
- content: 期待爱, 期待下一场旅行。
bottom_saying: Life is a long long journey.
# Content
excerpt_link: Read More

rss: /atom.xml

highlightjs: vs

# Works
works:
- works_name: TBA
  works_url: /

#duoshuo name
duoshuo:

#disqus name
disqus_shortname:

#fancybox
fancybox: true

# Miscellaneous
github: https://github.com/zib0
# twitter: https://twitter.com/
facebook: https://www.facebook.com/x.zibo.wang
# google: https://google.com/
# weibo: http://weibo.com/
email: mail@zibow.me

#about  timeline
timeline:
- num: 1996
  word: Born
- num: 2014
  word: Graduate from high school
- num: 2015
  word: Start bachelor degree at ANU 
- num: 2016
  word: Formal internship at Hewlett Packard Enterprise
- num: 2017
  word: Formal internship at Jun Xin Wei Ke
- num: 2018
  word: Developer at Questagame

#Links
links:
- name: Kieran
  link: http://go.kieran.top/

# Local search
# Dependencies: https://github.com/flashlab/hexo-generator-search
local_search:
  enable: true
  # if auto, trigger search by changing input
  # if manual, trigger search by pressing enter key or search button
  trigger: auto
  # show top n results per article, show all results by setting to -1
  top_n_per_article: 2
